[tool.poetry]
name = "rabbit-farm"
version = "6.0.0"
description = "Cultivates data from the database and sends them hopping to RabbitMQ queues, just like a bustling rabbit farm ğŸ°ğŸŒ¾."
authors = ["Bentley Hensel <bentleyhensel@gmail.com>"]
license = "AGPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Flask = "^3.0.0"
requests = "^2.31.0"
python-dotenv = "^1.0.0"
sentry-sdk = "^1.31.0"
pyroscope-io = "^0.8.5"
pika = "^1.3.2"
sqlalchemy = "^2.0.21"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
